language: cpp
os: linux
dist: focal

addons:
  sonarcloud:
    organization: "utilforever-github"
    token:
      secure: "B2UBKPgjXDCpPm7ZcafI5rUCkUCw5ZiKVrZile5ggSJZ1yBowrN/vZByKxp5vSPDoolSlLZIa7Pxfsn1dmSiga31nUUtwzGJg9mKzrlwPNWodCPPvMjnEJYt+IlVNslX2v/liWZYgE/sgr7jvXu1VMBZMCuRs8jUTLc3HGy6491ZjjzsaPG4UvSpq/mfu0/BWQ2qDa+HIrk0pOcgSG2qm0SwcOl+7E5f/WCS6JZleMPKL5/GgrFE6XuIiEfPB3e56xw+4mFlfTl98k07l+HJ1PuYmoilz6k7249e4x3CStEa741twEpcKHcA9OX6540OGrRyI2EJAhof/a9p11JgYIiDpvEr6trIC70FR13JMXAk2Uvr78GlCTORDCrZd8K1jbTmP84yLrKnI1qAImz94GRNShxxC4rZcWlTbQmojghzx1ZpfrgywGGiTm4eHIqXqCFuOxO4kAUOc6HzUriq2hp0qDZtimtFI5n36014UpXFhlnObtFSFgQOkoX9mKlY3WPOGL5NL8HQMpgi67B1kWWiL71x7COCqrTw0djPjNut0Ll7owrIvzitJbuuS/F9zzggQNF/FpdcL5YxCJvNoFyDZHkjqEFhI8chFTjDhEiX80IMAZfyC4rFA+IWxfar3J17lIND0LUSv1PszceVz4bTf02F/xu0TDSzpvKMUaE="

script:
  # Install packages
  - sudo apt-get install -yq gcovr ggcov lcov curl
  # Configure build
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_COVERAGE=ON
  # Wraps the compilation with the Build Wrapper to generate configuration
  # (used later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir ../bw-output make all
  # Execute some tests
  - lcov --gcov-tool /usr/bin/gcov -c -i -d test/unit_test -o base_unit_test.info
  - lcov --gcov-tool /usr/bin/gcov -c -i -d test/feature_test -o base_feature_test.info
  - bin/unit_test
  - bin/feature_test
  - lcov --gcov-tool /usr/bin/gcov -c -d test/unit_test -o unit_test.info
  - lcov --gcov-tool /usr/bin/gcov -c -d test/feature_test -o feature_test.info
  - lcov --gcov-tool /usr/bin/gcov -a base_unit_test.info -a base_feature_test.info -a unit_test.info -a feature_test.info -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '/usr/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -r coverage.info '*/external/*' -o coverage.info
  - lcov --gcov-tool /usr/bin/gcov -l coverage.info
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - cd ..
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'