name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          # macOS 10.15 + Xcode 11.7
          - name: "macOS 10.15 + Xcode 11.7"
            os: macos-10.15
            compiler: xcode
            version: "11.7"
          # macOS 10.15 + Xcode 12.0
          - name: "macOS 10.15 + Xcode 12.0"
            os: macos-10.15
            compiler: xcode
            version: "12.0"
          # macOS 10.15 + gcc-8
          - name: "macOS 10.15 + gcc-8"
            os: macos-10.15
            compiler: gcc
            version: "8"
          # macOS 10.15 + gcc-9
          - name: "macOS 10.15 + gcc-9"
            os: macos-10.15
            compiler: gcc
            version: "9"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/styler/styler/build/bin/unit_test