name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          # Ubuntu 16.04 + gcc-7
          - name: "Ubuntu 16.04 + gcc-7"
            os: ubuntu-16.04
            compiler: gcc
            version: "7"
          # Ubuntu 18.04 + gcc-8
          - name: "Ubuntu 18.04 + gcc-8"
            os: ubuntu-18.04
            compiler: gcc
            version: "8"
          # Ubuntu 20.04 + gcc-9
          - name: "Ubuntu 20.04 + gcc-9"
            os: ubuntu-20.04
            compiler: gcc
            version: "9"
          # Ubuntu 16.04 + clang-8
          - name: "Ubuntu 16.04 + clang-8"
            os: ubuntu-16.04
            compiler: clang
            version: "8"
          # Ubuntu 18.04 + clang-9
          - name: "Ubuntu 18.04 + clang-9"
            os: ubuntu-18.04
            compiler: clang
            version: "9"
          # Ubuntu 20.04 + clang-10
          - name: "Ubuntu 20.04 + clang-10"
            os: ubuntu-20.04
            compiler: clang
            version: "10"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cd build && make
    - name: Run Test
      run: /home/runner/work/styler/styler/build/bin/unit_test